# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xfdo_manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='xfdo_manager.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12xfdo_manager.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\nXFDOString\x12\x0e\n\x06string\x18\x01 \x01(\t\"<\n\x16XFDOPlayerAndPolicyNum\x12\x0e\n\x06player\x18\x01 \x01(\x03\x12\x12\n\npolicy_num\x18\x02 \x01(\x03\"\x1c\n\nXFDOPlayer\x12\x0e\n\x06player\x18\x01 \x01(\x03\".\n\x12XFDOPolicySpecJson\x12\x18\n\x10policy_spec_json\x18\x01 \x01(\t\"C\n\x12XFDOPolicySpecList\x12-\n\x10policy_spec_list\x18\x01 \x03(\x0b\x32\x13.XFDOPolicySpecJson\"\xa1\x01\n\x19XFDONewBestResponseParams\x12\x37\n\x1ametanash_specs_for_players\x18\x01 \x01(\x0b\x32\x13.XFDOPolicySpecList\x12\x37\n\x1a\x64\x65legate_specs_for_players\x18\x02 \x03(\x0b\x32\x13.XFDOPolicySpecList\x12\x12\n\npolicy_num\x18\x03 \x01(\x03\"V\n\x19XFDOPolicyMetadataRequest\x12\x0e\n\x06player\x18\x01 \x01(\x03\x12\x12\n\npolicy_num\x18\x02 \x01(\x03\x12\x15\n\rmetadata_json\x18\x03 \x01(\t\"\"\n\x10XFDOConfirmation\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32\x94\x02\n\x0bXFDOManager\x12\x32\n\tGetLogDir\x12\x16.google.protobuf.Empty\x1a\x0b.XFDOString\"\x00\x12J\n\x1d\x43laimNewActivePolicyForPlayer\x12\x0b.XFDOPlayer\x1a\x1a.XFDONewBestResponseParams\"\x00\x12\x46\n\x13SubmitFinalBRPolicy\x12\x1a.XFDOPolicyMetadataRequest\x1a\x11.XFDOConfirmation\"\x00\x12=\n\rIsPolicyFixed\x12\x17.XFDOPlayerAndPolicyNum\x1a\x11.XFDOConfirmation\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_XFDOSTRING = _descriptor.Descriptor(
  name='XFDOString',
  full_name='XFDOString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='string', full_name='XFDOString.string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=79,
)


_XFDOPLAYERANDPOLICYNUM = _descriptor.Descriptor(
  name='XFDOPlayerAndPolicyNum',
  full_name='XFDOPlayerAndPolicyNum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='XFDOPlayerAndPolicyNum.player', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='policy_num', full_name='XFDOPlayerAndPolicyNum.policy_num', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=141,
)


_XFDOPLAYER = _descriptor.Descriptor(
  name='XFDOPlayer',
  full_name='XFDOPlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='XFDOPlayer.player', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=171,
)


_XFDOPOLICYSPECJSON = _descriptor.Descriptor(
  name='XFDOPolicySpecJson',
  full_name='XFDOPolicySpecJson',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='policy_spec_json', full_name='XFDOPolicySpecJson.policy_spec_json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=219,
)


_XFDOPOLICYSPECLIST = _descriptor.Descriptor(
  name='XFDOPolicySpecList',
  full_name='XFDOPolicySpecList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='policy_spec_list', full_name='XFDOPolicySpecList.policy_spec_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=288,
)


_XFDONEWBESTRESPONSEPARAMS = _descriptor.Descriptor(
  name='XFDONewBestResponseParams',
  full_name='XFDONewBestResponseParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metanash_specs_for_players', full_name='XFDONewBestResponseParams.metanash_specs_for_players', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delegate_specs_for_players', full_name='XFDONewBestResponseParams.delegate_specs_for_players', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='policy_num', full_name='XFDONewBestResponseParams.policy_num', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=452,
)


_XFDOPOLICYMETADATAREQUEST = _descriptor.Descriptor(
  name='XFDOPolicyMetadataRequest',
  full_name='XFDOPolicyMetadataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='XFDOPolicyMetadataRequest.player', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='policy_num', full_name='XFDOPolicyMetadataRequest.policy_num', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata_json', full_name='XFDOPolicyMetadataRequest.metadata_json', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=540,
)


_XFDOCONFIRMATION = _descriptor.Descriptor(
  name='XFDOConfirmation',
  full_name='XFDOConfirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='XFDOConfirmation.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=542,
  serialized_end=576,
)

_XFDOPOLICYSPECLIST.fields_by_name['policy_spec_list'].message_type = _XFDOPOLICYSPECJSON
_XFDONEWBESTRESPONSEPARAMS.fields_by_name['metanash_specs_for_players'].message_type = _XFDOPOLICYSPECLIST
_XFDONEWBESTRESPONSEPARAMS.fields_by_name['delegate_specs_for_players'].message_type = _XFDOPOLICYSPECLIST
DESCRIPTOR.message_types_by_name['XFDOString'] = _XFDOSTRING
DESCRIPTOR.message_types_by_name['XFDOPlayerAndPolicyNum'] = _XFDOPLAYERANDPOLICYNUM
DESCRIPTOR.message_types_by_name['XFDOPlayer'] = _XFDOPLAYER
DESCRIPTOR.message_types_by_name['XFDOPolicySpecJson'] = _XFDOPOLICYSPECJSON
DESCRIPTOR.message_types_by_name['XFDOPolicySpecList'] = _XFDOPOLICYSPECLIST
DESCRIPTOR.message_types_by_name['XFDONewBestResponseParams'] = _XFDONEWBESTRESPONSEPARAMS
DESCRIPTOR.message_types_by_name['XFDOPolicyMetadataRequest'] = _XFDOPOLICYMETADATAREQUEST
DESCRIPTOR.message_types_by_name['XFDOConfirmation'] = _XFDOCONFIRMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

XFDOString = _reflection.GeneratedProtocolMessageType('XFDOString', (_message.Message,), {
  'DESCRIPTOR' : _XFDOSTRING,
  '__module__' : 'xfdo_manager_pb2'
  # @@protoc_insertion_point(class_scope:XFDOString)
  })
_sym_db.RegisterMessage(XFDOString)

XFDOPlayerAndPolicyNum = _reflection.GeneratedProtocolMessageType('XFDOPlayerAndPolicyNum', (_message.Message,), {
  'DESCRIPTOR' : _XFDOPLAYERANDPOLICYNUM,
  '__module__' : 'xfdo_manager_pb2'
  # @@protoc_insertion_point(class_scope:XFDOPlayerAndPolicyNum)
  })
_sym_db.RegisterMessage(XFDOPlayerAndPolicyNum)

XFDOPlayer = _reflection.GeneratedProtocolMessageType('XFDOPlayer', (_message.Message,), {
  'DESCRIPTOR' : _XFDOPLAYER,
  '__module__' : 'xfdo_manager_pb2'
  # @@protoc_insertion_point(class_scope:XFDOPlayer)
  })
_sym_db.RegisterMessage(XFDOPlayer)

XFDOPolicySpecJson = _reflection.GeneratedProtocolMessageType('XFDOPolicySpecJson', (_message.Message,), {
  'DESCRIPTOR' : _XFDOPOLICYSPECJSON,
  '__module__' : 'xfdo_manager_pb2'
  # @@protoc_insertion_point(class_scope:XFDOPolicySpecJson)
  })
_sym_db.RegisterMessage(XFDOPolicySpecJson)

XFDOPolicySpecList = _reflection.GeneratedProtocolMessageType('XFDOPolicySpecList', (_message.Message,), {
  'DESCRIPTOR' : _XFDOPOLICYSPECLIST,
  '__module__' : 'xfdo_manager_pb2'
  # @@protoc_insertion_point(class_scope:XFDOPolicySpecList)
  })
_sym_db.RegisterMessage(XFDOPolicySpecList)

XFDONewBestResponseParams = _reflection.GeneratedProtocolMessageType('XFDONewBestResponseParams', (_message.Message,), {
  'DESCRIPTOR' : _XFDONEWBESTRESPONSEPARAMS,
  '__module__' : 'xfdo_manager_pb2'
  # @@protoc_insertion_point(class_scope:XFDONewBestResponseParams)
  })
_sym_db.RegisterMessage(XFDONewBestResponseParams)

XFDOPolicyMetadataRequest = _reflection.GeneratedProtocolMessageType('XFDOPolicyMetadataRequest', (_message.Message,), {
  'DESCRIPTOR' : _XFDOPOLICYMETADATAREQUEST,
  '__module__' : 'xfdo_manager_pb2'
  # @@protoc_insertion_point(class_scope:XFDOPolicyMetadataRequest)
  })
_sym_db.RegisterMessage(XFDOPolicyMetadataRequest)

XFDOConfirmation = _reflection.GeneratedProtocolMessageType('XFDOConfirmation', (_message.Message,), {
  'DESCRIPTOR' : _XFDOCONFIRMATION,
  '__module__' : 'xfdo_manager_pb2'
  # @@protoc_insertion_point(class_scope:XFDOConfirmation)
  })
_sym_db.RegisterMessage(XFDOConfirmation)



_XFDOMANAGER = _descriptor.ServiceDescriptor(
  name='XFDOManager',
  full_name='XFDOManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=579,
  serialized_end=855,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLogDir',
    full_name='XFDOManager.GetLogDir',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_XFDOSTRING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ClaimNewActivePolicyForPlayer',
    full_name='XFDOManager.ClaimNewActivePolicyForPlayer',
    index=1,
    containing_service=None,
    input_type=_XFDOPLAYER,
    output_type=_XFDONEWBESTRESPONSEPARAMS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitFinalBRPolicy',
    full_name='XFDOManager.SubmitFinalBRPolicy',
    index=2,
    containing_service=None,
    input_type=_XFDOPOLICYMETADATAREQUEST,
    output_type=_XFDOCONFIRMATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='IsPolicyFixed',
    full_name='XFDOManager.IsPolicyFixed',
    index=3,
    containing_service=None,
    input_type=_XFDOPLAYERANDPOLICYNUM,
    output_type=_XFDOCONFIRMATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_XFDOMANAGER)

DESCRIPTOR.services_by_name['XFDOManager'] = _XFDOMANAGER

# @@protoc_insertion_point(module_scope)
