# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import xfdo_manager_pb2 as xfdo__manager__pb2


class XFDOManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLogDir = channel.unary_unary(
                '/XFDOManager/GetLogDir',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=xfdo__manager__pb2.XFDOString.FromString,
                )
        self.ClaimNewActivePolicyForPlayer = channel.unary_unary(
                '/XFDOManager/ClaimNewActivePolicyForPlayer',
                request_serializer=xfdo__manager__pb2.XFDOPlayer.SerializeToString,
                response_deserializer=xfdo__manager__pb2.XFDONewBestResponseParams.FromString,
                )
        self.SubmitFinalBRPolicy = channel.unary_unary(
                '/XFDOManager/SubmitFinalBRPolicy',
                request_serializer=xfdo__manager__pb2.XFDOPolicyMetadataRequest.SerializeToString,
                response_deserializer=xfdo__manager__pb2.XFDOConfirmation.FromString,
                )
        self.IsPolicyFixed = channel.unary_unary(
                '/XFDOManager/IsPolicyFixed',
                request_serializer=xfdo__manager__pb2.XFDOPlayerAndPolicyNum.SerializeToString,
                response_deserializer=xfdo__manager__pb2.XFDOConfirmation.FromString,
                )


class XFDOManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLogDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimNewActivePolicyForPlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitFinalBRPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsPolicyFixed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XFDOManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLogDir': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogDir,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=xfdo__manager__pb2.XFDOString.SerializeToString,
            ),
            'ClaimNewActivePolicyForPlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimNewActivePolicyForPlayer,
                    request_deserializer=xfdo__manager__pb2.XFDOPlayer.FromString,
                    response_serializer=xfdo__manager__pb2.XFDONewBestResponseParams.SerializeToString,
            ),
            'SubmitFinalBRPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitFinalBRPolicy,
                    request_deserializer=xfdo__manager__pb2.XFDOPolicyMetadataRequest.FromString,
                    response_serializer=xfdo__manager__pb2.XFDOConfirmation.SerializeToString,
            ),
            'IsPolicyFixed': grpc.unary_unary_rpc_method_handler(
                    servicer.IsPolicyFixed,
                    request_deserializer=xfdo__manager__pb2.XFDOPlayerAndPolicyNum.FromString,
                    response_serializer=xfdo__manager__pb2.XFDOConfirmation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'XFDOManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class XFDOManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLogDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/XFDOManager/GetLogDir',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            xfdo__manager__pb2.XFDOString.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClaimNewActivePolicyForPlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/XFDOManager/ClaimNewActivePolicyForPlayer',
            xfdo__manager__pb2.XFDOPlayer.SerializeToString,
            xfdo__manager__pb2.XFDONewBestResponseParams.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitFinalBRPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/XFDOManager/SubmitFinalBRPolicy',
            xfdo__manager__pb2.XFDOPolicyMetadataRequest.SerializeToString,
            xfdo__manager__pb2.XFDOConfirmation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsPolicyFixed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/XFDOManager/IsPolicyFixed',
            xfdo__manager__pb2.XFDOPlayerAndPolicyNum.SerializeToString,
            xfdo__manager__pb2.XFDOConfirmation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
